@startuml
title Melihat Barang
|U| User
|S| System
|D| Database
|U|
start
:Membuka halaman barang;
|S|
:Mengambil data barang;
|D|
:Mengirim data barang;
|S|
:Menampilkan halaman barang;
stop
@enduml
